// Products
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_LOADING = "SET_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_CURRENCY = "SET_CURRENCY";
// Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
// UI
export const CHANGE_SHOW_CURRENCIES = "CHANGE_SHOW_CURRENCIES";

export const CHANGE_SHOW_MINICART = "CHANGE_SHOW_MINICART";
